FROM php:8.3.3-apache AS development

# Instalar dependências
RUN apt-get update && \
    apt-get install -y libzip-dev zlib1g-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libicu-dev

# Habilitar módulos Apache
RUN a2enmod rewrite \
    && a2enmod headers

# Instalar extensões PHP
RUN docker-php-ext-install pdo_mysql zip mysqli gd intl

# Limpar cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN chmod -R -f 777 /var/www

CMD ["sh", "-c", "echo 'max_input_vars = 6000' >> /usr/local/etc/php/php.ini && apache2-foreground"]