version: '3.9'

services:

  moodle-db:
    image: mariadb:lts
    container_name: "moodle-db"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "moodle"
    volumes:
      - ../Database:/var/lib/mysql
    restart: always

  moodle:
    image: "moodle"
    container_name: "moodle"
    build: 
      context: "."
      target: "development"
      dockerfile: "dockerfile"
    ports:
      - "80:80"
    depends_on:
      - moodle-db
    volumes:
      - "../www:/var/www/html"
      - "./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "./apache/apache2.conf:/etc/apache2/apache2.conf"
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "phpmyadmin"
    links:
      - moodle-db:db
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "moodle"
      MYSQL_ROOT_PASSWORD: "root"
      PMA_ARBITRARY: "1"
    depends_on:
      - moodle-db
    restart: always
