FROM php:8.3.3-apache AS development

# Instalar dependências
RUN apt-get update && \
    apt-get install -y libzip-dev zlib1g-dev

# Habilitar módulos Apache
RUN a2enmod rewrite \
    && a2enmod headers

# Instalar extensões PHP
RUN docker-php-ext-install pdo_mysql zip

# Limpar cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*